"""test

Revision ID: 5a7be8892b3d
Revises: 
Create Date: 2025-07-24 04:57:47.929548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7be8892b3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('categories', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('products', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('products', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('storages', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('storages', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users_in_storages', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users_in_storages', 'updated_at',
               existing_type=sa.INTEGER(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_in_storages', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users_in_storages', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('storages', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('storages', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('products', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('products', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('categories', 'updated_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    op.alter_column('categories', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('(EXTRACT(epoch FROM CURRENT_TIMESTAMP))::integer'))
    # ### end Alembic commands ###
